micronautVersion=4.8.0
aux-cable.jlinkOptions=--verbose --strip-native-commands --strip-debug --no-header-files --no-man-pages --compress=zip-9
aux-cable.jvmOptions=-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
aux-cable.requiredModules=java.desktop,java.logging,jdk.unsupported,jdk.crypto.ec,jdk.zipfs
aux-cable.packaging.name=AuxCable
aux-cable.packaging.description=An open-source, cross-platform, and lightweight Aux Cable for your Discord servers.
aux-cable.packaging.editions=darwin,linux-x64,win-x64
aux-cable.packaging.editions.darwin.jvmOptions=-XstartOnFirstThread