import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";

import { Button } from "@/components/ui/button"
import {
    Form,
    FormControl,
    FormDescription,
    FormField,
    FormItem,
    FormLabel,
    FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input"
import {LogIn} from "lucide-react";
import {useHttp} from "@/contexts/http.ts";
import { Checkbox } from "@/components/ui/checkbox";
import {NewUserDialog} from "@/components/states/idle/new-user-dialog.tsx";
import {handleIfError} from "@/lib/error-handling.ts";

const formSchema = z.object({
    token: z.string().min(32),
    remember: z.boolean(),
});

export function LoginWithToken() {
    const http = useHttp();
    const form = useForm<z.infer<typeof formSchema>>({
        resolver: zodResolver(formSchema),
        defaultValues: {
            token: "",
            remember: false,
        },
    })

    const onSubmit = (values: z.infer<typeof formSchema>) => {
        http.post('/actions/login', values).then(handleIfError("action.login"))
    };

    return (
        <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
                <FormField
                    control={form.control}
                    name="token"
                    render={({ field }) => (
                        <FormItem>
                            <FormLabel>Bot Token</FormLabel>
                            <FormControl>
                                <Input {...field} type="password" autoComplete="off" />
                            </FormControl>
                            <FormDescription>
                                This is your bot's token, generated by Discord.
                                <NewUserDialog/>
                            </FormDescription>
                            <FormMessage />
                        </FormItem>
                    )}
                />
                <FormField
                    control={form.control}
                    name="remember"
                    render={({ field }) => (
                        <FormItem className="flex items-center space-x-1.5 space-y-0">
                            <FormControl>
                                <Checkbox
                                    checked={field.value}
                                    onCheckedChange={field.onChange}
                                />
                            </FormControl>
                            <FormLabel className="font-semibold">Remember account</FormLabel>
                        </FormItem>
                    )}
                />
                <div className="flex justify-end items-end">
                    <Button variant="default" type="submit">Login<LogIn/></Button>
                </div>
            </form>
        </Form>
    )
}