name: Gradle Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            tasks: "npmInstall build"
          - os: macos-latest
            tasks: "npmInstall distJpackage"
          - os: windows-latest
            tasks: "npmInstall distJpackage"
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'


      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle
        run: ./gradlew ${{ matrix.tasks }}

      - name: Cleanup artifacts
        run: |
          mkdir gh-artifact
          echo "=========== Main JARs ==========="
          ls ./build/libs/*-all.jar
          mv ./build/libs/*-all.jar ./gh-artifact/ || true
          echo "=========== Optimized JARs ==========="
          ls ./packaging/**/build/libs/*
          mv ./packaging/**/build/libs/* ./gh-artifact/ || true
          echo "=========== Distributions ==========="
          ls ./packaging/**/build/distributions/*
          mv ./packaging/**/build/distributions/* ./gh-artifact/ || true
          echo "=========== Result ==========="
          ls ./gh-artifact/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: package-${{ matrix.os }}
          path: ./gh-artifact/*

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs: build
    steps:
      - name: Merge package artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          delete-merged: true

      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          name: 'merged-artifacts'
          path: .
          merge-multiple: true

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ inputs.version }}
        run: |
          gh release create --draft $VERSION "gh-artifact/*"